In [59]:
import pandas as pd

In [60]:
df = pd.read_csv("glassdoor_jobs.csv")
df = df[df['Salary Estimate'] != '-1']
df.tail(50)

,Unnamed: 0,Job Title,Salary Estimate,Job Description,Rating,Company Name,Location,Headquarters,Size,Founded,Type of ownership,Industry,Sector,Revenue,Competitors
892,892,Jr. Data Scientist,$81K-$132K (Glassdoor est.),MITRE\nis a trusted operator of federally fund...,3.2,MITRE\n3.2,"McLean, VA","Bedford, MA",5001 to 10000 employees,1958,Nonprofit Organization,Federal Agencies,Government,$1 to $2 billion (USD),"Battelle, General Atomics, SAIC"
893,893,Senior Data Scientist,Employer Provided Salary:$120K-$140K,"SkySync is a dynamic, fast-paced, venture-back...",5.0,SkySync\n5.0,"Ann Arbor, MI","Ann Arbor, MI",51 to 200 employees,2011,Company - Private,Computer Hardware & Software,Information Technology,Unknown / Non-Applicable,-1
895,895,Products Data Analyst II,$90K-$157K (Glassdoor est.),TriNet is a leading provider of comprehensive ...,3.3,TriNet\n3.3,"Dublin, CA","Dublin, CA",1001 to 5000 employees,1988,Company - Public,Consulting,Business Services,$2 to $5 billion (USD),"Paychex, Insperity, ADP"
896,896,Data Architect / Data Modeler,$63K-$110K (Glassdoor est.),Medidata: Conquering Diseases Together\n\nMedi...,4.3,Medidata Solutions\n4.3,"New York, NY","New York, NY",1001 to 5000 employees,1999,Company - Public,Enterprise Software & Network Solutions,Information Technology,$500 million to $1 billion (USD),Oracle
897,897,Analytics Manager - Data Mart,$42K-$86K (Glassdoor est.),We have an opportunity to join the Alliance as...,3.5,Central California Alliance for Health\n3.5,"Scotts Valley, CA","Scotts Valley, CA",501 to 1000 employees,1996,Nonprofit Organization,Health Care Services & Hospitals,Health Care,$500 million to $1 billion (USD),-1
898,898,Lead Data Analyst,$32K-$62K (Glassdoor est.),JOB DESCRIPTION:\n\nSignpost is looking for a ...,3.9,Signpost\n3.9,"New York, NY","New York, NY",201 to 500 employees,2010,Company - Private,Internet,Information Technology,$10 to $25 million (USD),-1
899,899,Data Science Engineer - Mobile,$116K-$208K (Glassdoor est.),Mobile is a top strategic priority for Adobe. ...,4.0,Adobe\n4.0,"San Jose, CA","San Jose, CA",10000+ employees,1982,Company - Public,Computer Hardware & Software,Information Technology,$5 to $10 billion (USD),"Apple, Microsoft"
900,900,Senior Data Scientist Oncology,$107K-$173K (Glassdoor est.),At AstraZeneca we are constantly pushing the b...,3.9,AstraZeneca\n3.9,"Gaithersburg, MD","Cambridge, United Kingdom",10000+ employees,1913,Company - Public,Biotech & Pharmaceuticals,Biotech & Pharmaceuticals,$10+ billion (USD),"Roche, GlaxoSmithKline, Novartis"
901,901,Data Scientist,$65K-$113K (Glassdoor est.),DatamanUSA has an exciting opportunity for a D...,3.4,"DatamanUSA, LLC\n3.4","Olympia, WA","Centennial, CO",51 to 200 employees,-1,Company - Private,IT Services,Information Technology,$5 to $10 million (USD),-1
902,902,Sr. Data Engineer - Contract-to-Hire (Java),$69K-$127K (Glassdoor est.),As we strive to make a better day for our gues...,3.0,Pilot Flying J Travel Centers LLC\n3.0,"Knoxville, TN","Knoxville, TN",10000+ employees,1958,Company - Private,Gas Stations,Retail,$10+ billion (USD),"TravelCenters of America, Love's Travel Stops ..."
904,904,Senior Data Scientist - R&D Oncology,$102K-$172K (Glassdoor est.),"At AstraZeneca,we work together to deliver inn...",3.9,AstraZeneca\n3.9,"New York, NY","Cambridge, United Kingdom",10000+ employees,1913,Company - Public,Biotech & Pharmaceuticals,Biotech & Pharmaceuticals,$10+ billion (USD),"Roche, GlaxoSmithKline, Novartis"
907,907,Data Engineer,$74K-$124K (Glassdoor est.),"Pinnacol Assurance does just one thing, and do...",4.0,Pinnacol Assurance\n4.0,"Denver, CO","Denver, CO",501 to 1000 employees,1915,Nonprofit Organization,Insurance Carriers,Insurance,$500 million to $1 billion (USD),-1
909,909,Food Scientist - Developer,$40K-$68K (Glassdoor est.),Palermo Villa Inc. is interested in a high-ene...,3.3,Palermo's Pizza\n3.3,"Milwaukee, WI","Milwaukee, WI",501 to 1000 employees,1964,Company - Private,Food & Beverage Manufacturing,Manufacturing,Unknown / Non-Applicable,-1
910,910,Senior Data Engineer,$76K-$142K (Glassdoor est.),Sr. Data Engineer FTE for Franklin\n\nThere ar...,3.2,Equian LLC\n3.2,"Franklin, TN","Indianapolis, IN",1001 to 5000 employees,2004,Company - Private,Health Care Services & Hospitals,Health Care,Unknown / Non-Applicable,-1
911,911,Data Engineer,$76K-$142K (Glassdoor est.),MetroStar Systems is looking for a Data Engine...,3.4,MetroStar Systems\n3.4,"Rockville, MD","Reston, VA",201 to 500 employees,1999,Company - Private,IT Services,Information Technology,$25 to $50 million (USD),-1
912,912,Senior Data Scientist,$108K-$171K (Glassdoor est.),"The Infrastructure, Architecture, and Tools te...",4.4,MathWorks\n4.4,"Natick, MA","Natick, MA",1001 to 5000 employees,1984,Company - Private,Computer Hardware & Software,Information Technology,$1 to $2 billion (USD),-1
913,913,"Director II, Data Science - GRM Actuarial",$202K-$306K (Glassdoor est.),Advance your career at Liberty Mutual Insuranc...,3.3,Liberty Mutual Insurance\n3.3,"Chicago, IL","Boston, MA",10000+ employees,1912,Company - Private,Insurance Carriers,Insurance,$10+ billion (USD),"Travelers, Allstate, State Farm"
914,914,Machine Learning Engineer,$91K-$159K (Glassdoor est.),We are seeking a highly-experienced ML Enginee...,3.2,Information Builders\n3.2,"New York, NY","New York, NY",1001 to 5000 employees,1975,Company - Private,Computer Hardware & Software,Information Technology,Unknown / Non-Applicable,"Qlik, Tableau Software, Informatica"
916,916,"Sr Expert Data Science, Advanced Visual Analyt...",$80K-$133K (Glassdoor est.),"Posting Title\nSr Expert Data Science, Advance...",3.8,Novartis\n3.8,"Cambridge, MA","Basel, Switzerland",10000+ employees,1996,Company - Public,Biotech & Pharmaceuticals,Biotech & Pharmaceuticals,$10+ billion (USD),-1
919,919,MED TECH/LAB SCIENTIST- SOUTH COASTAL LAB,$21-$34 Per Hour(Glassdoor est.),Day Shift: 7A-330P. Holidays and every other w...,3.6,Beebe Healthcare\n3.6,"Millville, DE","Lewes, DE",1001 to 5000 employees,1935,Nonprofit Organization,Health Care Services & Hospitals,Health Care,$100 to $500 million (USD),-1
920,920,"Scientist, Molecular/Cellular Biologist",$49K-$97K (Glassdoor est.),"[1]Scientist, Molecular/Cellular Biologist\n\n...",2.9,Audentes Therapeutics\n2.9,"South San Francisco, CA","San Francisco, CA",201 to 500 employees,2012,Subsidiary or Business Segment,Biotech & Pharmaceuticals,Biotech & Pharmaceuticals,Unknown / Non-Applicable,"BioMarin Pharmaceutical, Sangamo Therapeutics,..."
921,921,Staff Scientist-Downstream Process Development,$49K-$113K (Glassdoor est.),ABL is seeking a Staff Scientist for the Downs...,2.7,Advanced BioScience Laboratories\n2.7,"Rockville, MD","Rockville, MD",201 to 500 employees,1961,Company - Private,Biotech & Pharmaceuticals,Biotech & Pharmaceuticals,$25 to $50 million (USD),-1
924,924,Data Scientist,$96K-$161K (Glassdoor est.),SummaryProvide data management and statistical...,3.2,"Numeric, LLC\n3.2","Philadelphia, PA","Chadds Ford, PA",1 to 50 employees,-1,Company - Private,Staffing & Outsourcing,Business Services,$5 to $10 million (USD),-1
926,926,Scientist - Analytical Services,$65K-$134K (Glassdoor est.),British American Tobacco\nReynolds American In...,3.1,Reynolds American\n3.1,"Winston-Salem, NC","Winston-Salem, NC",5001 to 10000 employees,1875,Company - Private,Consumer Products Manufacturing,Manufacturing,$10+ billion (USD),-1
928,928,"Associate Scientist / Sr. Associate Scientist,...",$59K-$125K (Glassdoor est.),"Who we are\n\n23andMe, the leading consumer ge...",4.0,23andMe\n4.0,"South San Francisco, CA","Sunnyvale, CA",501 to 1000 employees,2006,Company - Private,Biotech & Pharmaceuticals,Biotech & Pharmaceuticals,Unknown / Non-Applicable,"Ancestry, Verily Life Sciences, Abbott Laborat..."
929,929,Associate Data Analyst- Graduate Development P...,$32K-$59K (Glassdoor est.),Overview\n\n\nNational Interstate is a member ...,3.3,National Interstate\n3.3,"Richfield, OH","Richfield, OH",501 to 1000 employees,1989,Company - Private,Insurance Carriers,Insurance,$500 million to $1 billion (USD),-1
930,930,Sr. Data Engineer,$87K-$158K (Glassdoor est.),Join our team of Data Consultants and work on ...,4.5,Moser Consulting\n4.5,"Indianapolis, IN","Indianapolis, IN",51 to 200 employees,1996,Company - Private,Consulting,Business Services,$25 to $50 million (USD),-1
931,931,Clinical Data Analyst,$27K-$48K (Glassdoor est.),Job Summary\n\n\nGreenway Health is actively s...,3.0,Greenway Health\n3.0,"Tampa, FL","Tampa, FL",1001 to 5000 employees,1977,Subsidiary or Business Segment,Enterprise Software & Network Solutions,Information Technology,$100 to $500 million (USD),"eClinicalWorks, NextGen Healthcare, athenahealth"
932,932,IT Associate Data Analyst,$39K-$69K (Glassdoor est.),"Monday, November 25, 2019\n\nOur Personal Line...",3.7,The Hanover Insurance Group\n3.7,"Worcester, MA","Worcester, MA",5001 to 10000 employees,1852,Company - Public,Insurance Carriers,Insurance,$5 to $10 billion (USD),-1
933,933,Business Data Analyst,$36K-$71K (Glassdoor est.),(We are unable to sponsor for this role now or...,3.8,Fareportal\n3.8,"New York, NY","New York, NY",1001 to 5000 employees,2002,Company - Private,Travel Agencies,Travel & Tourism,$2 to $5 billion (USD),"Expedia Group, Orbitz Worldwide, Priceline.com"
934,934,Senior Insurance Data Scientist,$107K-$173K (Glassdoor est.),"What We'll Bring:\n\nAt TransUnion, we have a ...",3.9,TransUnion\n3.9,"Chicago, IL","Chicago, IL",5001 to 10000 employees,1968,Company - Public,Financial Analytics & Research,Finance,$1 to $2 billion (USD),-1
935,935,Senior Data Science Systems Engineer,$56K-$99K (Glassdoor est.),"MITRE’s Army Concepts, Platforms and Theater O...",3.2,MITRE\n3.2,"Hampton, VA","Bedford, MA",5001 to 10000 employees,1958,Nonprofit Organization,Federal Agencies,Government,$1 to $2 billion (USD),"Battelle, General Atomics, SAIC"
936,936,ENVIRONMENTAL ENGINEER/SCIENTIST,Employer Provided Salary:$25-$28 Per Hour,"McPhail Associates, LLC is a geotechnical and ...",3.3,Mcphail Associates\n3.3,"Cambridge, MA","Cambridge, MA",1 to 50 employees,1976,Company - Private,Construction,"Construction, Repair & Maintenance",Unknown / Non-Applicable,-1
938,938,Senior Scientist - Regulatory Submissions,$80K-$155K (Glassdoor est.),British American Tobacco\nReynolds American In...,3.1,Reynolds American\n3.1,"Winston-Salem, NC","Winston-Salem, NC",5001 to 10000 employees,1875,Company - Private,Consumer Products Manufacturing,Manufacturing,$10+ billion (USD),-1
939,939,Scientist - Biomarker and Flow Cytometry,$43K-$98K (Glassdoor est.),"Crown Bioscience, a JSR Life Sciences company,...",2.4,Crown Bioscience\n2.4,"San Diego, CA","San Diego, CA",501 to 1000 employees,2006,Company - Private,Biotech & Pharmaceuticals,Biotech & Pharmaceuticals,$50 to $100 million (USD),-1
940,940,Revenue Analytics Manager,$45K-$78K (Glassdoor est.),HOVER uses patented technology making it possi...,4.8,HOVER\n4.8,"San Francisco, CA","San Francisco, CA",51 to 200 employees,2011,Company - Private,Computer Hardware & Software,Information Technology,$25 to $50 million (USD),-1
941,941,Sr. Scientist Method Development,$50K-$110K (Glassdoor est.),Q2 Solutions is a leading clinical trial labor...,2.9,Q2 Solutions\n2.9,"Marietta, GA","Morrisville, NC",1001 to 5000 employees,2015,Company - Private,Biotech & Pharmaceuticals,Biotech & Pharmaceuticals,Unknown / Non-Applicable,-1
942,942,"Associate Scientist, LC/MS Biologics",$44K-$96K (Glassdoor est.),Q2 Solutions is a leading clinical trial labor...,2.9,Q2 Solutions\n2.9,"Ithaca, NY","Morrisville, NC",1001 to 5000 employees,2015,Company - Private,Biotech & Pharmaceuticals,Biotech & Pharmaceuticals,Unknown / Non-Applicable,-1
943,943,"Research Scientist, Immunology - Cancer Biology",Employer Provided Salary:$100K-$140K,"Research Scientist, Immunology - Cancer Biolog...",-1.0,Kronos Bio,"Cambridge, MA","San Mateo, CA",Unknown,-1,Company - Private,-1,-1,Unknown / Non-Applicable,-1
944,944,IT - Data Engineer II,$61K-$119K (Glassdoor est.),IT - Data Engineer II\n\nThe Data Engineer II ...,3.4,Arbella Insurance\n3.4,"Quincy, MA","Quincy, MA",1001 to 5000 employees,1988,Company - Private,Insurance Carriers,Insurance,$100 to $500 million (USD),-1
945,945,Machine Learning Engineer (NLP),$80K-$142K (Glassdoor est.),CK-12’s mission is to provide free access to o...,4.1,CK-12 Foundation\n4.1,"Palo Alto, CA","Palo Alto, CA",1 to 50 employees,2007,Company - Private,K-12 Education,Education,Unknown / Non-Applicable,-1
946,946,Senior Data Analyst,$99K-$178K (Glassdoor est.),Senior Data Analyst\n\nAbout us\n\n\nLife360 b...,3.9,Life360\n3.9,"San Francisco, CA","San Francisco, CA",51 to 200 employees,2008,Company - Public,Computer Hardware & Software,Information Technology,Unknown / Non-Applicable,-1
947,947,Data Science Project Manager,$37K-$100K (Glassdoor est.),"At MassMutual, we are passionate about helping...",3.6,MassMutual\n3.6,"Boston, MA","Springfield, MA",5001 to 10000 employees,1851,Company - Private,Insurance Carriers,Insurance,$10+ billion (USD),-1
948,948,Data Engineer,$62K-$113K (Glassdoor est.),Do you find data architecture exciting? Does b...,3.9,Fivestars\n3.9,"San Francisco, CA","San Francisco, CA",201 to 500 employees,2011,Company - Private,Internet,Information Technology,$100 to $500 million (USD),"Belly, SpotOn"
949,949,"Principal, Data Science - Advanced Analytics",$86K-$137K (Glassdoor est.),IQVIA is the leading human data science compan...,3.6,IQVIA\n3.6,"Plymouth Meeting, PA","Durham, NC",10000+ employees,2017,Company - Public,Biotech & Pharmaceuticals,Biotech & Pharmaceuticals,$2 to $5 billion (USD),"PPD, INC Research, PRA Health Sciences"
950,950,"Sr Scientist, Immuno-Oncology - Oncology",$58K-$111K (Glassdoor est.),Site Name: USA - Massachusetts - Cambridge\nPo...,3.9,GSK\n3.9,"Cambridge, MA","Brentford, United Kingdom",10000+ employees,1830,Company - Public,Biotech & Pharmaceuticals,Biotech & Pharmaceuticals,$10+ billion (USD),"Pfizer, AstraZeneca, Merck"
951,951,Senior Data Engineer,$72K-$133K (Glassdoor est.),THE CHALLENGE\nEventbrite has a world-class da...,4.4,Eventbrite\n4.4,"Nashville, TN","San Francisco, CA",1001 to 5000 employees,2006,Company - Public,Internet,Information Technology,$100 to $500 million (USD),"See Tickets, TicketWeb, Vendini"
952,952,"Project Scientist - Auton Lab, Robotics Institute",$56K-$91K (Glassdoor est.),The Auton Lab at Carnegie Mellon University is...,2.6,Software Engineering Institute\n2.6,"Pittsburgh, PA","Pittsburgh, PA",501 to 1000 employees,1984,College / University,Colleges & Universities,Education,Unknown / Non-Applicable,-1
953,953,Data Science Manager,$95K-$160K (Glassdoor est.),Data Science ManagerResponsibilities:\n\nOvers...,3.2,"Numeric, LLC\n3.2","Allentown, PA","Chadds Ford, PA",1 to 50 employees,-1,Company - Private,Staffing & Outsourcing,Business Services,$5 to $10 million (USD),-1
955,955,Research Scientist – Security and Privacy,$61K-$126K (Glassdoor est.),Returning Candidate? Log back in to the Career...,3.6,Riverside Research Institute\n3.6,"Beavercreek, OH","Arlington, VA",501 to 1000 employees,1967,Nonprofit Organization,Federal Agencies,Government,$50 to $100 million (USD),-1

In [31]:
salary = df['Salary Estimate'].apply(lambda x: x.split('(')[0])

In [32]:
salary.head(50)

0                               $53K-$91K
1                              $63K-$112K
2                               $80K-$90K
3                               $56K-$97K
4                              $86K-$143K
5                              $71K-$119K
6                               $54K-$93K
7                              $86K-$142K
8                               $38K-$84K
9                             $120K-$160K
10                            $126K-$201K
11                             $64K-$106K
12                            $106K-$172K
13                              $46K-$85K
14                             $83K-$144K
15                            $102K-$190K
16                             $67K-$137K
17                            $118K-$189K
18                            $110K-$175K
19                             $64K-$111K
20                             $81K-$130K
21                             $73K-$119K
22                             $86K-$139K
23                             $63K-$105K
25                            $109K-$177K
26                             $63K-$110K
27                             $75K-$124K
28                              $34K-$61K
29                             $63K-$105K
30                              $80K-$90K
31                              $56K-$97K
32                             $72K-$120K
33                             $86K-$143K
34                             $93K-$149K
35                             $85K-$140K
36                             $77K-$135K
37                             $82K-$132K
38                             $83K-$137K
39                            $115K-$180K
40                             $74K-$138K
41                             $64K-$112K
43                             $68K-$129K
44                            $110K-$175K
45                             $52K-$113K
46                             $110K-$150K
48    Employer Provided Salary:$150K-$160K
49                            $158K-$211K
50                              $20K-$39K
51                             $56K-$117K
52                              $63K-$99K
Name: Salary Estimate, dtype: object

In [76]:
remove_kd_salary = salary.apply(lambda x: x.replace('$','').replace('K',''))

In [93]:
df['employer_provided'] = df['Salary Estimate'].apply(lambda x: 1 if 'employer provided salary:' in x.lower() else 0)

In [91]:
df['hr_min'] = remove_kd_salary.apply(lambda x: x.lower().replace('per hour','').replace('employer provided salary:',''))

In [88]:
df['min_salary'] = df['hr_min'].apply(lambda x: int(x.split('-')[0]))

In [92]:
df['max_salary'] = df['hr_min'].apply(lambda x: int(x.split('-')[1]))

In [95]:
df['avg_salary'] = (df.min_salary+df.max_salary)/2

In [101]:
#check company name
df['Company text'] = df.apply(lambda x: x['Company Name'] if x['Rating'] < 0 else x['Company Name'][:-3],axis=1)

In [104]:
df['Company text'] = df['Company text'].apply(lambda x: x.replace('\n',''))

In [106]:
# take location for state
df['Job_state'] = df['Location'].apply(lambda x: x.split(',')[1])

In [107]:
#how many jobs are available in each state
df['Job_state'].value_counts()

 CA             151
 MA             103
 NY              72
 VA              41
 IL              40
 MD              35
 PA              33
 TX              28
 NC              21
 WA              21
 NJ              17
 FL              16
 OH              14
 TN              13
 DC              11
 CO              11
 UT              10
 WI              10
 IN              10
 AZ               9
 MO               9
 AL               8
 DE               6
 GA               6
 MI               6
 KY               6
 CT               5
 IA               5
 LA               4
 OR               4
 NE               4
 KS               3
 NM               3
 MN               2
 ID               2
 SC               1
 Los Angeles      1
 RI               1
Name: Job_state, dtype: int64

In [108]:
df.columns

Index(['Unnamed: 0', 'Job Title', 'Salary Estimate', 'Job Description',
       'Rating', 'Company Name', 'Location', 'Headquarters', 'Size', 'Founded',
       'Type of ownership', 'Industry', 'Sector', 'Revenue', 'Competitors',
       'max_salary', 'hourly', 'employer_provided', 'hr_min', 'min_salary',
       'avg_salary', 'Company text', 'Job_state'],
      dtype='object')

In [110]:
#check to see if the job position is at the headquarters
df['same_state'] = df.apply(lambda x: 1 if x.Headquarters == x.Location else 0, axis = 1)

In [112]:
# age of company
df['age_of_company'] = df['Founded'].apply(lambda x: x if x < 0 else 2020-x)

In [117]:
#python requirement
df['python_req'] = df['Job Description'].apply(lambda x: 1 if 'python' in x.lower() else 0)
df['python_req'].value_counts()

1    392
0    350
Name: python_req, dtype: int64

In [119]:
df['r_req'] = df['Job Description'].apply(lambda x: 1 if 'r studio' in x.lower() or 'r-studio' in x.lower() else 0)
df['r_req'].value_counts()

0    740
1      2
Name: r_req, dtype: int64

In [120]:
df['apache_req'] = df['Job Description'].apply(lambda x: 1 if 'apache' in x.lower() or 'apache spark' in x.lower() else 0)
df['apache_req'].value_counts()

0    709
1     33
Name: apache_req, dtype: int64

In [121]:
df['aws_req'] = df['Job Description'].apply(lambda x: 1 if 'aws' in x.lower() else 0)
df['aws_req'].value_counts()

0    566
1    176
Name: aws_req, dtype: int64

In [122]:
df['excel_req'] = df['Job Description'].apply(lambda x: 1 if 'excel' in x.lower() else 0)
df['excel_req'].value_counts()

1    388
0    354
Name: excel_req, dtype: int64

In [125]:
df_out = df.drop(['Unnamed: 0'],axis=1)

In [127]:
df_out.to_csv('salary_data_cleaned.csv',index = False)